name: Sync Leetcode

on:
  workflow_dispatch:  
  schedule:
    - cron: "45 23 * * *"  # Runs at 7:45 PM Eastern (EDT or EST)


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: my-folder
          filter-duplicate-secs: true

